version: '3.8'

services:
  apache:
    build: ./apache
    ports:
      - "${APACHE_PORT}:80"
    volumes:
      - ./apache/www:/var/www/html
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
  
  python:
    build: ./python
    volumes:
      - ./python:/app
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      ARANGODB_HOST: ${ARANGODB_HOST}
      ARANGODB_USER: ${ARANGODB_USER}
      ARANGODB_PASSWORD: ${ARANGODB_PASSWORD}
      OPENAI_API_KEY: ${OPENAI_API_KEY}

  mysql:
    build:
      context: ./mysql
      args:
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf   